[[ACCOUNTS]]
address = "rBhGj6Hn2MMDe3Jf9toPmqGRxgYbq6RHTR"  


website = "https://www.xrinu.org/"
logo = "https://gateway.pinata.cloud/ipfs/QmWuDutWBMp7h2WLsdYa37jyZfnQth8DsGWnDedSyBgBq8"

[CURRENCIES]
code = "XRINU"
issuer = "rBhGj6Hn2MMDe3Jf9toPmqGRxgYbq6RHTR"
description = "XRINU is a fast, low-cost utility token on the XRP Ledger."
