[[ACCOUNTS]]
address = "rBhGj6Hn2MMDe3Jf9toPmqGRxgYbq6RHTR"  


website = "https://www.xrinu.org/"
logo = "logo = "https://raw.githubusercontent.com/Aldcode/xrinu-metadata/main/assets/UltimateLlamaLogo2025.png"


[CURRENCIES]
code = "XRINU"
issuer = "rBhGj6Hn2MMDe3Jf9toPmqGRxgYbq6RHTR"
description = "XRINU is a fast, low-cost utility token on the XRP Ledger."
